= IdIcon

Simple implementation of an identicon service.

== Usage

HTTP `GET` is used to request an identicon image.

....
curl http://localhost:8000/avatar/23463b99b62a72f26ed677cc556c44e8?s=100&c=v2
....

Instead of requesting identicons for MD5 hashes of usernames or mail addresses, it is possible to use plain username and mail address. The will result in the same generated identicon.

Use request query parameter `s` to request images with specified size. Default value is 80px. The size is limited to a maximum value of 512px.

Query parameter `c` will set color scheme. Available values are `v1`, `v2` and `gh`.
The latter resembles the color scheme used by GitHub.

The request query parameter `d` can be used to request GitHub like patterns by setting the value to `github`.

=== Configuration

Configuration is available by using environment variables.

You can use `COLORSCHEME` to define the default color scheme to be used. Fallback value will be `v2`.

The `PATTERN` environment variable is available to define GitHub like patterns as default by using `github`.

=== Docker build

Use `Dockerfile` to build a new image based on `scratch` image and start this image by typing

....
$ docker build -t idicon .
$ docker run -p 8000:8000 idicon
....

This will build the image and will start a new container listening on port 8000 for requests.
